# Generated by Django 5.2.8 on 2025-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('added', 'Added to Group'), ('status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('group_deleted', 'Group Deleted')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
