# Generated by Django 5.2.8 on 2025-12-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pramiti_ai', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
